import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

// The app is Next.js App Router, and only that. The TanStack Start scaffold this
// config used to work around was removed once it was established that app/
// imports nothing from it; two rules here existed solely to hold it at arm's
// length and had outlived it:
//
//   - `src/**` and `vite.config.ts` were ignored. Both are gone.
//   - `server-only` was a restricted import, on the grounds that "TanStack Start
//     does not use the Next.js server-only package". True, and no longer the
//     point: this is a Next app, `server-only` is how Next keeps server modules
//     out of the client bundle, and the rule was banning the correct tool for
//     the framework in use.
//
// react-refresh went with them. Its only-export-components rule is a Vite
// convention, and under the App Router a page exporting a constant beside its
// component is ordinary — the rule had nothing left to warn about but that.
export default tseslint.config(
  // next-env.d.ts is generated by Next on every build and is a triple-slash
  // reference by design; linting it only ever reports Next's own file back.
  { ignores: ["dist", ".next", "node_modules", "next-env.d.ts"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
