-- Give BaoTheX a vocabulary for the sport it actually covers.
--
-- Until now the entity table held seven strength-training rows, so entity
-- extraction tagged 2 of 593 daily articles and clustering had nothing to work
-- with but trigram title similarity — which left 88% of clusters holding a
-- single article and merged English with Vietnamese coverage exactly once in
-- the entire database. Ten outlets covering one match sat in ten clusters, and
-- none of them looked hot.
--
-- Aliases are matched by process.ExtractEntities with a case-insensitive
-- word-boundary regex, so they are the whole point: "Messi" is "Messi" in both
-- languages, which is what lets a Vietnamese and an English report about the
-- same event finally land in one cluster.
--
-- ALIAS RULES (violating these poisons the data quietly):
--   * No bare ambiguous words. "City" matches "New York City", "United" matches
--     "United States", "Real" matches ordinary prose, "Euro" matches currency.
--     Always qualify: "Man City", "Man Utd", "Real Madrid".
--   * Aliases under 3 characters are ignored by the extractor — don't bother.
--   * Prefer a missed mention over a false one: a wrong entity corrupts
--     clustering for every article that touches it.
--
-- expertise carries the sport slug so a later query can group by discipline
-- without another join.

INSERT INTO entities (slug, name, kind, expertise, aliases) VALUES

-- ============ BÓNG ĐÁ QUỐC TẾ — câu lạc bộ ============
('manchester-united', 'Manchester United', 'club', '{bong-da-quoc-te}',
  '{"Manchester United","Man United","Man Utd","Quỷ đỏ"}'),
('manchester-city', 'Manchester City', 'club', '{bong-da-quoc-te}',
  '{"Manchester City","Man City"}'),
('liverpool', 'Liverpool', 'club', '{bong-da-quoc-te}',
  '{"Liverpool","Lữ đoàn đỏ","The Kop"}'),
('arsenal', 'Arsenal', 'club', '{bong-da-quoc-te}',
  '{"Arsenal","Pháo thủ"}'),
('chelsea', 'Chelsea', 'club', '{bong-da-quoc-te}',
  '{"Chelsea"}'),
('tottenham', 'Tottenham Hotspur', 'club', '{bong-da-quoc-te}',
  '{"Tottenham","Spurs","Gà trống"}'),
('newcastle', 'Newcastle United', 'club', '{bong-da-quoc-te}',
  '{"Newcastle","Chích chòe"}'),
('aston-villa', 'Aston Villa', 'club', '{bong-da-quoc-te}', '{"Aston Villa"}'),
('west-ham', 'West Ham United', 'club', '{bong-da-quoc-te}', '{"West Ham"}'),
('everton', 'Everton', 'club', '{bong-da-quoc-te}', '{"Everton"}'),
('real-madrid', 'Real Madrid', 'club', '{bong-da-quoc-te}',
  '{"Real Madrid","Kền kền trắng","Los Blancos"}'),
('barcelona', 'FC Barcelona', 'club', '{bong-da-quoc-te}',
  '{"Barcelona","Barca","Barça","Blaugrana"}'),
('atletico-madrid', 'Atlético Madrid', 'club', '{bong-da-quoc-te}',
  '{"Atletico Madrid","Atlético Madrid","Atletico"}'),
('sevilla', 'Sevilla FC', 'club', '{bong-da-quoc-te}', '{"Sevilla"}'),
('juventus', 'Juventus', 'club', '{bong-da-quoc-te}',
  '{"Juventus","Juve","Bà đầm già"}'),
('inter-milan', 'Inter Milan', 'club', '{bong-da-quoc-te}',
  '{"Inter Milan","Nerazzurri"}'),
('ac-milan', 'AC Milan', 'club', '{bong-da-quoc-te}',
  '{"AC Milan","Rossoneri"}'),
('napoli', 'Napoli', 'club', '{bong-da-quoc-te}', '{"Napoli"}'),
('as-roma', 'AS Roma', 'club', '{bong-da-quoc-te}', '{"AS Roma","Roma"}'),
('bayern-munich', 'Bayern Munich', 'club', '{bong-da-quoc-te}',
  '{"Bayern Munich","Bayern","Hùm xám"}'),
('borussia-dortmund', 'Borussia Dortmund', 'club', '{bong-da-quoc-te}',
  '{"Borussia Dortmund","Dortmund"}'),
('bayer-leverkusen', 'Bayer Leverkusen', 'club', '{bong-da-quoc-te}',
  '{"Bayer Leverkusen","Leverkusen"}'),
('psg', 'Paris Saint-Germain', 'club', '{bong-da-quoc-te}',
  '{"Paris Saint-Germain","PSG"}'),
('marseille', 'Olympique Marseille', 'club', '{bong-da-quoc-te}', '{"Marseille"}'),
('ajax', 'AFC Ajax', 'club', '{bong-da-quoc-te}', '{"Ajax"}'),
('benfica', 'SL Benfica', 'club', '{bong-da-quoc-te}', '{"Benfica"}'),
('porto', 'FC Porto', 'club', '{bong-da-quoc-te}', '{"FC Porto"}'),

-- ============ BÓNG ĐÁ QUỐC TẾ — cầu thủ ============
('lionel-messi', 'Lionel Messi', 'athlete', '{bong-da-quoc-te}',
  '{"Lionel Messi","Messi"}'),
('cristiano-ronaldo', 'Cristiano Ronaldo', 'athlete', '{bong-da-quoc-te}',
  '{"Cristiano Ronaldo","Ronaldo","CR7"}'),
('kylian-mbappe', 'Kylian Mbappé', 'athlete', '{bong-da-quoc-te}',
  '{"Kylian Mbappe","Kylian Mbappé","Mbappe","Mbappé"}'),
('erling-haaland', 'Erling Haaland', 'athlete', '{bong-da-quoc-te}',
  '{"Erling Haaland","Haaland"}'),
('jude-bellingham', 'Jude Bellingham', 'athlete', '{bong-da-quoc-te}',
  '{"Jude Bellingham","Bellingham"}'),
('vinicius-junior', 'Vinícius Júnior', 'athlete', '{bong-da-quoc-te}',
  '{"Vinicius Junior","Vinícius Júnior","Vinicius","Vinícius","Vini Jr"}'),
('mohamed-salah', 'Mohamed Salah', 'athlete', '{bong-da-quoc-te}',
  '{"Mohamed Salah","Salah"}'),
('kevin-de-bruyne', 'Kevin De Bruyne', 'athlete', '{bong-da-quoc-te}',
  '{"Kevin De Bruyne","De Bruyne"}'),
('harry-kane', 'Harry Kane', 'athlete', '{bong-da-quoc-te}', '{"Harry Kane"}'),
('bukayo-saka', 'Bukayo Saka', 'athlete', '{bong-da-quoc-te}',
  '{"Bukayo Saka","Saka"}'),
('lamine-yamal', 'Lamine Yamal', 'athlete', '{bong-da-quoc-te}',
  '{"Lamine Yamal","Yamal"}'),
('rodri', 'Rodri', 'athlete', '{bong-da-quoc-te}', '{"Rodri"}'),
('robert-lewandowski', 'Robert Lewandowski', 'athlete', '{bong-da-quoc-te}',
  '{"Robert Lewandowski","Lewandowski"}'),
('neymar', 'Neymar', 'athlete', '{bong-da-quoc-te}', '{"Neymar"}'),
('declan-rice', 'Declan Rice', 'athlete', '{bong-da-quoc-te}', '{"Declan Rice"}'),

-- ============ BÓNG ĐÁ QUỐC TẾ — huấn luyện viên ============
('pep-guardiola', 'Pep Guardiola', 'coach', '{bong-da-quoc-te}',
  '{"Pep Guardiola","Guardiola"}'),
('jurgen-klopp', 'Jürgen Klopp', 'coach', '{bong-da-quoc-te}',
  '{"Jurgen Klopp","Jürgen Klopp","Klopp"}'),
('carlo-ancelotti', 'Carlo Ancelotti', 'coach', '{bong-da-quoc-te}',
  '{"Carlo Ancelotti","Ancelotti"}'),
('mikel-arteta', 'Mikel Arteta', 'coach', '{bong-da-quoc-te}',
  '{"Mikel Arteta","Arteta"}'),
('thomas-tuchel', 'Thomas Tuchel', 'coach', '{bong-da-quoc-te}',
  '{"Thomas Tuchel","Tuchel"}'),
('lionel-scaloni', 'Lionel Scaloni', 'coach', '{bong-da-quoc-te}',
  '{"Lionel Scaloni","Scaloni"}'),

-- ============ BÓNG ĐÁ — giải đấu ============
('premier-league', 'Premier League', 'competition', '{bong-da-quoc-te}',
  '{"Premier League","Ngoại hạng Anh","EPL"}'),
('la-liga', 'La Liga', 'competition', '{bong-da-quoc-te}', '{"La Liga","LaLiga"}'),
('serie-a', 'Serie A', 'competition', '{bong-da-quoc-te}', '{"Serie A"}'),
('bundesliga', 'Bundesliga', 'competition', '{bong-da-quoc-te}', '{"Bundesliga"}'),
('ligue-1', 'Ligue 1', 'competition', '{bong-da-quoc-te}', '{"Ligue 1"}'),
('champions-league', 'UEFA Champions League', 'competition', '{bong-da-quoc-te}',
  '{"Champions League","Cúp C1"}'),
('europa-league', 'UEFA Europa League', 'competition', '{bong-da-quoc-te}',
  '{"Europa League"}'),
('world-cup', 'FIFA World Cup', 'competition', '{bong-da-quoc-te}',
  '{"World Cup","FIFA World Cup"}'),
('copa-america', 'Copa América', 'competition', '{bong-da-quoc-te}',
  '{"Copa America","Copa América"}'),

-- ============ BÓNG ĐÁ — đội tuyển quốc gia ============
('england-nt', 'Đội tuyển Anh', 'national_team', '{bong-da-quoc-te}',
  '{"tuyển Anh","đội tuyển Anh","Tam sư"}'),
('argentina-nt', 'Đội tuyển Argentina', 'national_team', '{bong-da-quoc-te}',
  '{"tuyển Argentina","đội tuyển Argentina","Albiceleste"}'),
('brazil-nt', 'Đội tuyển Brazil', 'national_team', '{bong-da-quoc-te}',
  '{"tuyển Brazil","đội tuyển Brazil","Selecao","Seleção"}'),
('france-nt', 'Đội tuyển Pháp', 'national_team', '{bong-da-quoc-te}',
  '{"tuyển Pháp","đội tuyển Pháp","Les Bleus"}'),
('spain-nt', 'Đội tuyển Tây Ban Nha', 'national_team', '{bong-da-quoc-te}',
  '{"tuyển Tây Ban Nha","đội tuyển Tây Ban Nha","La Roja"}'),

-- ============ BÓNG ĐÁ — liên đoàn ============
('fifa', 'FIFA', 'federation', '{bong-da-quoc-te}', '{"FIFA"}'),
('uefa', 'UEFA', 'federation', '{bong-da-quoc-te}', '{"UEFA"}'),
('afc', 'AFC', 'federation', '{bong-da-viet-nam}', '{"AFC"}'),

-- ============ BÓNG ĐÁ VIỆT NAM ============
('vietnam-nt', 'Đội tuyển Việt Nam', 'national_team', '{bong-da-viet-nam}',
  '{"đội tuyển Việt Nam","tuyển Việt Nam","ĐT Việt Nam","Những chiến binh sao vàng"}'),
('u23-vietnam', 'U23 Việt Nam', 'national_team', '{bong-da-viet-nam}',
  '{"U23 Việt Nam","U-23 Việt Nam"}'),
('v-league', 'V.League 1', 'competition', '{bong-da-viet-nam}',
  '{"V-League","V.League","VLeague"}'),
('vff', 'Liên đoàn bóng đá Việt Nam', 'federation', '{bong-da-viet-nam}',
  '{"VFF","Liên đoàn bóng đá Việt Nam"}'),
('vpf', 'VPF', 'federation', '{bong-da-viet-nam}', '{"VPF"}'),
('hanoi-fc', 'Hà Nội FC', 'club', '{bong-da-viet-nam}',
  '{"Hà Nội FC","CLB Hà Nội"}'),
('hagl', 'Hoàng Anh Gia Lai', 'club', '{bong-da-viet-nam}',
  '{"Hoàng Anh Gia Lai","HAGL"}'),
('the-cong-viettel', 'Thể Công Viettel', 'club', '{bong-da-viet-nam}',
  '{"Thể Công Viettel","Thể Công"}'),
('cahn', 'Công an Hà Nội', 'club', '{bong-da-viet-nam}',
  '{"Công an Hà Nội","CAHN"}'),
('nam-dinh', 'Thép Xanh Nam Định', 'club', '{bong-da-viet-nam}',
  '{"Thép Xanh Nam Định","Nam Định"}'),
('binh-duong', 'Becamex Bình Dương', 'club', '{bong-da-viet-nam}',
  '{"Becamex Bình Dương","Bình Dương"}'),
('quang-hai', 'Nguyễn Quang Hải', 'athlete', '{bong-da-viet-nam}',
  '{"Nguyễn Quang Hải","Quang Hải"}'),
('tien-linh', 'Nguyễn Tiến Linh', 'athlete', '{bong-da-viet-nam}',
  '{"Nguyễn Tiến Linh","Tiến Linh"}'),
('van-lam', 'Đặng Văn Lâm', 'athlete', '{bong-da-viet-nam}',
  '{"Đặng Văn Lâm","Văn Lâm"}'),
('cong-phuong', 'Nguyễn Công Phượng', 'athlete', '{bong-da-viet-nam}',
  '{"Nguyễn Công Phượng","Công Phượng"}'),
('van-hau', 'Đoàn Văn Hậu', 'athlete', '{bong-da-viet-nam}',
  '{"Đoàn Văn Hậu","Văn Hậu"}'),
('hoang-duc', 'Nguyễn Hoàng Đức', 'athlete', '{bong-da-viet-nam}',
  '{"Nguyễn Hoàng Đức","Hoàng Đức"}'),

-- ============ TENNIS ============
('atp', 'ATP Tour', 'federation', '{tennis}', '{"ATP Tour","ATP"}'),
('wta', 'WTA Tour', 'federation', '{tennis}', '{"WTA Tour","WTA"}'),
('wimbledon', 'Wimbledon', 'competition', '{tennis}', '{"Wimbledon"}'),
('roland-garros', 'Roland Garros', 'competition', '{tennis}',
  '{"Roland Garros","French Open"}'),
('us-open-tennis', 'US Open', 'competition', '{tennis}', '{"US Open"}'),
('australian-open', 'Australian Open', 'competition', '{tennis}', '{"Australian Open"}'),
('novak-djokovic', 'Novak Djokovic', 'athlete', '{tennis}',
  '{"Novak Djokovic","Djokovic"}'),
('carlos-alcaraz', 'Carlos Alcaraz', 'athlete', '{tennis}',
  '{"Carlos Alcaraz","Alcaraz"}'),
('jannik-sinner', 'Jannik Sinner', 'athlete', '{tennis}',
  '{"Jannik Sinner","Sinner"}'),
('rafael-nadal', 'Rafael Nadal', 'athlete', '{tennis}',
  '{"Rafael Nadal","Nadal"}'),
('iga-swiatek', 'Iga Świątek', 'athlete', '{tennis}',
  '{"Iga Swiatek","Iga Świątek","Swiatek","Świątek"}'),
('aryna-sabalenka', 'Aryna Sabalenka', 'athlete', '{tennis}',
  '{"Aryna Sabalenka","Sabalenka"}'),
('coco-gauff', 'Coco Gauff', 'athlete', '{tennis}', '{"Coco Gauff","Gauff"}'),

-- ============ BÓNG RỔ ============
('nba', 'NBA', 'competition', '{bong-ro}', '{"NBA"}'),
('vba', 'VBA', 'competition', '{bong-ro}', '{"VBA"}'),
('la-lakers', 'Los Angeles Lakers', 'club', '{bong-ro}',
  '{"Los Angeles Lakers","LA Lakers","Lakers"}'),
('golden-state-warriors', 'Golden State Warriors', 'club', '{bong-ro}',
  '{"Golden State Warriors","Warriors"}'),
('boston-celtics', 'Boston Celtics', 'club', '{bong-ro}',
  '{"Boston Celtics","Celtics"}'),
('denver-nuggets', 'Denver Nuggets', 'club', '{bong-ro}',
  '{"Denver Nuggets","Nuggets"}'),
('lebron-james', 'LeBron James', 'athlete', '{bong-ro}',
  '{"LeBron James","LeBron"}'),
('stephen-curry', 'Stephen Curry', 'athlete', '{bong-ro}',
  '{"Stephen Curry","Steph Curry"}'),
('nikola-jokic', 'Nikola Jokić', 'athlete', '{bong-ro}',
  '{"Nikola Jokic","Nikola Jokić","Jokic","Jokić"}'),
('giannis-antetokounmpo', 'Giannis Antetokounmpo', 'athlete', '{bong-ro}',
  '{"Giannis Antetokounmpo","Giannis","Antetokounmpo"}'),
('luka-doncic', 'Luka Dončić', 'athlete', '{bong-ro}',
  '{"Luka Doncic","Luka Dončić","Doncic","Dončić"}'),

-- ============ F1 & THỂ THAO MOTOR ============
('formula-1', 'Formula 1', 'competition', '{f1-the-thao-motor}',
  '{"Formula 1","Formula One"}'),
('red-bull-racing', 'Red Bull Racing', 'club', '{f1-the-thao-motor}',
  '{"Red Bull Racing"}'),
('scuderia-ferrari', 'Scuderia Ferrari', 'club', '{f1-the-thao-motor}',
  '{"Scuderia Ferrari","Ferrari"}'),
('mercedes-f1', 'Mercedes-AMG F1', 'club', '{f1-the-thao-motor}',
  '{"Mercedes-AMG","Mercedes F1"}'),
('mclaren-f1', 'McLaren F1', 'club', '{f1-the-thao-motor}',
  '{"McLaren"}'),
('max-verstappen', 'Max Verstappen', 'athlete', '{f1-the-thao-motor}',
  '{"Max Verstappen","Verstappen"}'),
('lewis-hamilton', 'Lewis Hamilton', 'athlete', '{f1-the-thao-motor}',
  '{"Lewis Hamilton","Hamilton"}'),
('charles-leclerc', 'Charles Leclerc', 'athlete', '{f1-the-thao-motor}',
  '{"Charles Leclerc","Leclerc"}'),
('lando-norris', 'Lando Norris', 'athlete', '{f1-the-thao-motor}',
  '{"Lando Norris","Norris"}'),

-- ============ THỂ THAO ĐIỆN TỬ ============
('league-of-legends', 'League of Legends', 'competition', '{the-thao-dien-tu}',
  '{"League of Legends","Liên Minh Huyền Thoại","LMHT"}'),
('valorant', 'VALORANT', 'competition', '{the-thao-dien-tu}', '{"VALORANT"}'),
('counter-strike', 'Counter-Strike 2', 'competition', '{the-thao-dien-tu}',
  '{"Counter-Strike","CS2"}'),
('dota-2', 'Dota 2', 'competition', '{the-thao-dien-tu}', '{"Dota 2"}'),
('vcs', 'VCS', 'competition', '{the-thao-dien-tu}',
  '{"VCS","Vietnam Championship Series"}'),
('gam-esports', 'GAM Esports', 'club', '{the-thao-dien-tu}',
  '{"GAM Esports"}'),
('t1', 'T1', 'club', '{the-thao-dien-tu}', '{"T1 Esports"}'),
('worlds-lol', 'LoL World Championship', 'competition', '{the-thao-dien-tu}',
  '{"LoL World Championship","CKTG"}'),

-- ============ CẦU LÔNG & CÁC MÔN KHÁC ============
('bwf', 'BWF', 'federation', '{cau-long}', '{"BWF"}'),
('nguyen-thuy-linh', 'Nguyễn Thùy Linh', 'athlete', '{cau-long}',
  '{"Nguyễn Thùy Linh","Thùy Linh"}'),
('nguyen-tien-minh', 'Nguyễn Tiến Minh', 'athlete', '{cau-long}',
  '{"Nguyễn Tiến Minh","Tiến Minh"}'),
('olympics', 'Thế vận hội Olympic', 'competition', '{the-thao-khac}',
  '{"Olympic","Olympics","Thế vận hội"}'),
('sea-games', 'SEA Games', 'competition', '{the-thao-viet-nam}',
  '{"SEA Games"}'),
('asiad', 'ASIAD', 'competition', '{the-thao-viet-nam}',
  '{"ASIAD","Asian Games"}'),
('nguyen-thi-oanh', 'Nguyễn Thị Oanh', 'athlete', '{the-thao-viet-nam}',
  '{"Nguyễn Thị Oanh"}'),
('nguyen-huy-hoang', 'Nguyễn Huy Hoàng', 'athlete', '{the-thao-viet-nam}',
  '{"Nguyễn Huy Hoàng"}')

ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  kind = EXCLUDED.kind,
  expertise = EXCLUDED.expertise,
  aliases = EXCLUDED.aliases;
